name: 'ReSharper CLI InspectCode'
description: 'Inspect code with ReSharper Command Line Tool and annotate PR'
author: 'muno92'
inputs:
  solutionPath:
    required: true
    description: Path to Solution file to be inspected.
  failOnIssue:
    required: false
    default: '1'
    description: Whether the action should fail if there are any issues.
  version:
    required: false
    description: Version of the Resharper CLI tool to install. Defaults to the latest available.
  minimumReportSeverity:
    required: false
    description: Minimum severity for issues to be reported. Defaults to "HINT". [INFO, HINT, SUGGESTION, WARNING, ERROR]
    default: 'hint'
  minimumSeverity:
    required: false
    description: Minimum severity for issues to cause the action to fail. Defaults to "notice". Ignored if failOnIssue is set to '0'.
    default: 'notice'
  exclude:
    required: false
    description: Relative path(s) or file masks that define which files to exclude during the inspection.
  include:
    required: false
    description: Relative path(s) or file masks that define which files to include during the inspection.
  workingDirectory:
    required: false
    description: The working directory in which to run the `jb` command and to which all paths/patterns are relative.
  ignoreIssueType:
    required: false
    description: Comma-separated list of issue types to ignore.
  solutionWideAnalysis:
    required: false
    description: Explicitly enable or disable solution-wide analysis. If not specified, solution-wide analysis will be enabled or disabled based on the existing settings.
  extensions:
    required: false
    description: Comma-separated list of extensions to install.
  noBuild:
    required: false
    default: 'false'
    description: Let you specify whether to build the target solution before starting the analysis. By default (false), InspectCode always builds the solution.
  cachesHome:
    required: false
    description: Lets you specify a custom location for the data that InspectCode caches.
  properties:
    required: false
    description: Lets you override MSBuild properties. You can use a semicolon to separate multiple properties --properties:prop1=val1;prop2=val2.
  dotnetVersion:
    required: false
    description: Lets you specify the version of the .NET SDK to use.
  verbosity:
    required: false
    description: Sets the verbosity level of the output. [OFF, FATAL, ERROR, WARN, INFO, VERBOSE, TRACE]
runs:
  using: 'node24'
  main: 'dist/index.js'
branding:
  icon: hash
  color: orange
