name: 'ReSharper CLI InspectCode'
description: 'Inspect code with ReSharper Command Line Tool and annotate PR'
author: 'muno92'
inputs:
  solutionPath:
    required: true
    description: 'input solution file path here'
  failOnIssue:
    required: false
    default: '1'
    description:  'action fail when issue exists'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: hash
  color: orange
